#!/usr/bin/env python3
"""Scrub AI metadata from model18unaltered.xlsx → unbesiegbarmodel1.xlsx.

Preserves all formulas and hardcoded numbers. Strips cell comments and removes
AI indicator phrases from text cells only.

Run:  cd LULU/scripts && python3 scrub_unbesiegbarmodel.py
"""
from __future__ import annotations

import re
import shutil
from pathlib import Path

import openpyxl

ROOT = Path(__file__).resolve().parents[1]
INPUT = ROOT / "model18unaltered.xlsx"
OUTPUT = ROOT / "unbesiegbarmodel1.xlsx"

AI_INDICATORS = [
    "agent",
    "firecrawl",
    "chatgpt",
    "openai",
    "anthropic",
    "claude",
    "gemini",
    "large language model",
    "llm",
    "as an ai",
    "ai model",
    "ai-generated",
    "generated by ai",
    "language model",
    "sure, i can help",
    "certainly!",
]

PATTERN = re.compile(
    r"(?i)\b(?:" + "|".join(map(re.escape, AI_INDICATORS)) + r")\b"
)


def scrub_workbook(src: Path = INPUT, dst: Path = OUTPUT) -> Path:
    if not src.exists():
        raise FileNotFoundError(src)
    tmp = dst.with_suffix(".scrubbing.xlsx")
    shutil.copy2(src, tmp)
    wb = openpyxl.load_workbook(tmp)
    scrubbed_cells = 0
    removed_comments = 0

    for ws in wb.worksheets:
        for row in ws.iter_rows():
            for cell in row:
                if cell.comment:
                    cell.comment = None
                    removed_comments += 1
                if cell.value and isinstance(cell.value, str):
                    if cell.value.startswith("="):
                        continue
                    new_value = PATTERN.sub("", cell.value)
                    new_value = " ".join(new_value.split())
                    if new_value != cell.value:
                        cell.value = new_value if new_value else None
                        scrubbed_cells += 1

    wb.save(tmp)
    tmp.replace(dst)
    print(f"Saved {dst}")
    print(f"  Scrubbed text cells: {scrubbed_cells}")
    print(f"  Removed comments:    {removed_comments}")
    return dst


def verify(src: Path = INPUT, dst: Path = OUTPUT) -> None:
    src_wb = openpyxl.load_workbook(src, data_only=False)
    dst_wb = openpyxl.load_workbook(dst, data_only=False)
    formula_diffs = []
    value_diffs = []

    for sheet in src_wb.sheetnames:
        s_ws = src_wb[sheet]
        d_ws = dst_wb[sheet]
        for row in range(1, max(s_ws.max_row, d_ws.max_row) + 1):
            for col in range(1, max(s_ws.max_column, d_ws.max_column) + 1):
                sv = s_ws.cell(row, col).value
                dv = d_ws.cell(row, col).value
                if isinstance(sv, str) and sv.startswith("="):
                    if sv != dv:
                        formula_diffs.append(f"{sheet}!{openpyxl.utils.get_column_letter(col)}{row}")
                elif not isinstance(sv, str) or not sv.startswith("="):
                    if sv != dv and not (
                        isinstance(sv, str)
                        and isinstance(dv, str)
                        and PATTERN.sub("", sv).strip() == (dv or "").strip()
                    ):
                        if isinstance(sv, str) and PATTERN.search(sv):
                            continue
                        if sv != dv:
                            value_diffs.append(
                                f"{sheet}!{openpyxl.utils.get_column_letter(col)}{row}: {sv!r} -> {dv!r}"
                            )

    if formula_diffs:
        raise AssertionError("Formulas changed:\n" + "\n".join(formula_diffs[:10]))

    hits = []
    for ws in dst_wb.worksheets:
        for row in ws.iter_rows():
            for cell in row:
                if isinstance(cell.value, str) and PATTERN.search(cell.value):
                    hits.append(f"{ws.title}!{cell.coordinate}")
    if hits:
        raise AssertionError(f"Residual AI indicators: {hits}")

    print("Verify OK: formulas unchanged, AI indicators removed")


if __name__ == "__main__":
    out = scrub_workbook()
    verify(INPUT, out)
